### ISSUE TITLE
Form filtering dropdown is present on all edit screens

### ISSUE THREAD

**Issue by k1sul1** [anttiviljami/wp-libre-form#11]
![problem](http://i.imgur.com/x6O8igx.png)

As you can see from the image, the filtering dropdown is visible on all edit.php screens in wp-admin, instead of just showing up on the wplf-form edit page.

**Comment by anttiviljami** [comment]
Good catch ! Probably an easy fix. You on it ?

**Comment by k1sul1** [comment]
Yeah I can take a look at it tomorrow, I'm going to need to do a client callback function for another project, so I can probably kill this one on the same go.

**Comment by anttiviljami** [comment]
awesome ! :)
