### ISSUE TITLE
Not possible to send the default email copy with custom headers and / or attachments

### ISSUE THREAD

**Issue by k1sul1** [anttiviljami/wp-libre-form#19]
As you can see [here](https://github.com/anttiviljami/wp-libre-form/blob/5eee793caff63f3c15ed914fb5a77474cfff2e00/inc/wplf-form-actions.php#L28), wp_mail is only passed 3 parameters, and there is no way to add extra headers or attachments using the default email copy. 

One might argue that users should create their own email copy template if they want to do such things, but for most of the time, the default one is fine, and lazy users like me would rather not do that if possible. 

Possible solution, passing the filterable default values to wp_mail: 
```php
    $to = isset($form_meta['_wplf_email_copy_to']) ? $form_meta['_wplf_email_copy_to'][0] : get_option( 'admin_email' );
    $subject = wp_sprintf( __('New submission from %s', 'wp-libre-form'), $referrer );
    $content = wp_sprintf( __('Form "%s" (ID %d) was submitted with values below: ', 'wp-libre-form'), $form_title, $form_id ) . "\n\n";
    $headers = apply_filters( 'wplf_email_copy_headers', '' );
    $attachments = apply_filters( 'wplf_email_copy_attachments', array() );
    foreach( $_POST as $key => $value ) {
      if( '_' === $key[0] ) {
        continue;
      }
      $content .= esc_html( $key ) . ': ' . esc_html( print_r( $value, true ) ) . "\n";
    }
    wp_mail( $to, $subject, $content, $headers, $attachments );
```

That way users could add new headers and attachments while keeping the default template.

**Comment by anttiviljami** [comment]
While at it, why not add filters for all the other default wp_mail params ?

I'm all for this idea. However, shouldn't the values be NULL instead of empty `''` and `array()` ?

**Comment by k1sul1** [comment]
Yeah, why not. 

[The documentation](https://developer.wordpress.org/reference/functions/wp_mail/) says that '' is the default value for $headers and array() is the default value for $attachments. Otherwise I would pass NULL like you said.

**Comment by timiwahalahti** [comment]
In my current project, it would be really helpful to have filter for `$to` and possibility to change that depending on referrer page metadata.  Think I'm going to make a fork and PR tomorrow.

**Comment by timiwahalahti** [comment]
So there's PR #22 which adds referrer id as a hidden field, headers and attachments to email and filters for email content.

Next thing what would be nice, is filter or some other way to change field key to be more understandable for end user. But that's another story in another issue.
