### ISSUE TITLE
No support for input type=file

### ISSUE THREAD

**Issue by danielck** [anttiviljami/wp-libre-form#2]
I tried your plugin out of curiosity, and of course had to test the statement of "any valid HTML form" :)

`<input type="file">` fields do not work, not even the raw file path is submitted. The first obstacle here seems to be that forms need to have `enctype='multipart/form-data'` in the form tag or apparently file fields are completely ignored.

Secondly the file inputs could be handled with `wp_handle_upload()` and `wp_insert_attachment()`.

**Comment by anttiviljami** [comment]
Hmm, hadn't actually tested that. Thanks for letting me know!

You're right; the form needs to send `multipart/form-data` in order for uploads to work. Not sure yet how I should implement this, there need to be some sort of limits for the file inputs when done from the public side. 

I might just use `media_handle_upload` by default, but file upload behaviour should be configurable via a filter.

I guess "any valid HTML form" is too bold of a statement. I'll just need to keep working on it.

Thanks for your contribution! :)

**Comment by anttiviljami** [comment]
Native file upload support is now fully added as of 5eee793caff63f3c15ed914fb5a77474cfff2e00 👍
