### ISSUE TITLE
Make wplf-form post type unpublic

### ISSUE THREAD

**Issue by timiwahalahti** [anttiviljami/wp-libre-form#23]
I think that forms should not be public. In most of the use cases (at least when i'm using), those are used via shortcode rather than linking directly to single form. Public single forms shows up in search engines and sitemaps, which isn't that nice. Especially if theme developer has forgotten to style basic single page for some reason.

Antti likes to have preview of form, and that's important in my opinion too. Preview can't be achieved unless post type is public, but maybe we could make a redirect when entering single form if you're role is subscriber or you haven't logged in. Other possible way that comes to my mind, is render form in html below editor while editing it. Kinda same way as field detector works now.

**Comment by timiwahalahti** [comment]
Oh, actually. Making a redirect isn't by far best practice in this situation, setting 404 would be a much better solution (props @TeemuSuoranta).

`add_action( 'wp', 'maybe_show_404_on_wplf_single' );
function maybe_show_404_on_wplf_single() {
  if( !current_user_can( 'edit_post' ) && is_singular( 'wplf-form' ) ) {
    global $wp_query;
    $wp_query->set_404();
  }
}`

This way post type is public, preview and single view works for logged in users, but visitor gets 404. Google does not index 404, but there may still be issues with some plugins that generates sitemaps. However it's better situation than current, at least in my opinion.

There is also need for setting to disabling this feature on single forms, maybe a filter to disable it in all forms. Also a notification or some sort of message in editor or form view is needed to indicate that this don't work unless you are logged in.

Any thoughts? Because of time related matters, I wouldn't want to do PR if it wont be merged.

**Comment by anttiviljami** [comment]
LGTML! If you can test and PR this, I'll gladly merge this :)

Awesome !

**Comment by timiwahalahti** [comment]
There's PR now, #31.

I'we tested it, but maybe it would be good if you and @k1sul1 could test it also before merge?

**Comment by k1sul1** [comment]
Seems to work, just tested. Looks very good. 

However, do we really need yet another metabox? Right now we have 3 metaboxes on the side, wouldn't just one be enough? 

![metaboxes](http://i.imgur.com/CO9mopB.png)

Or is it just me?

**Comment by k1sul1** [comment]
I found a bug in vigorous testing. 

![bug](http://i.imgur.com/D5CL40m.png)

This text seems to appear on other post types too, such as page.

**Comment by anttiviljami** [comment]
We definitely don't need the metabox. I don't see a use case for `/wplf-form/myform` urls. Better to just hide them

**Comment by timiwahalahti** [comment]
@k1sul1 good catch! That's what happens when you submit PR after midnight 😹 

If metabox if removed, maybe that filter and notice should be kept tho?

**Comment by anttiviljami** [comment]
:+1: for the notice

Having the filter is ok. Just make sure forms are non-public by default. :) Now it seems to be the other way round.

Thanks <3

**Comment by timiwahalahti** [comment]
PR is now updated; meta box got removed and permalink notice in post.php fixed to show up only when editing `wplf-form` post type.

Forms have been non-public, but I did double-check that now.
