### ISSUE TITLE
Email copy to address not working after value changed to empty

### ISSUE THREAD

**Issue by timiwahalahti** [anttiviljami/wp-libre-form#25]
In single form, set email address for copy, save, remove address and save again.

This causes empty `_wplf_email_copy_to` meta for form, and code only checks if that meta is set. Either fix that check in `wplf-form-actions.php` to ignore empty, or use `delete_post_meta` function instead of `update_post_meta` and false as as value.

**Comment by anttiviljami** [comment]
Good catch! :) I've made this mistake like a million times now. I never learn :)
