### ISSUE TITLE
Allow class editing from editor

### ISSUE THREAD

**Issue by k1sul1** [anttiviljami/wp-libre-form#3]
After a brief look on the source, it's already possible to add extra classes to the form element using the "hidden" shortcode attribute xclass, but it would be definitely easier if you could edit them directly in the editor instead of `do_shortcode('[libre-form id="332" xclass="extra"]');`. 

Useful for analytics & visual purposes. 

And just maybe, mention about this somewhere: https://github.com/anttiviljami/wp-libre-form/blob/master/classes/class-cpt-wplf-form.php#L466

**Comment by anttiviljami** [comment]
You're suggesting adding a metabox for xclasses to the form editor page?

**Comment by anttiviljami** [comment]
Good point about the xclasses attr being hidden! :+1:

Should mention it at least in the readme.

**Comment by k1sul1** [comment]
Yes for a metabox, and probably while at it allow setting an id-attribute too. 

I know from experience that the guys who usually manage analytics can be very picky.

**Comment by anttiviljami** [comment]
Setting an id might indeed be useful. Not quite sure about the metabox thing yet. Will have a think about it.

**Comment by k1sul1** [comment]
Any thoughts on this?

**Comment by anttiviljami** [comment]
I'm still not big on the metabox for classes idea. There's already the xclass shortcode attribute

**Comment by k1sul1** [comment]
Reasonable, but what about other attributes? #9

What if there were an attributes box, where you could add & edit any attributes applied on the form element? That wouldn't concern just the class attribute.

**Comment by anttiviljami** [comment]
Sounds good to me. Just need to make sure it doesn't interfere with the xclass shortcode attr and merges the classes properly.

**Comment by anttiviljami** [comment]
Let's continue discussion on #9
