### ISSUE TITLE
Unable to submit form on (static) frontpage when form is embedded via ACF-field

### ISSUE THREAD

**Issue by k1sul1** [anttiviljami/wp-libre-form#4]
I've static frontpage, and I'm using Advanced Custom Fields options-page to add the form to said page footer. The shortcode works fine, the form is displayed and so on, but when trying to submit the form, the user is then directed to a 404-page and you can see the form details in the address bar.

After a brief look I noticed that for some reason wplf-form.js isn't included on this page. Forms work fine if the user is on a single page.

**Comment by anttiviljami** [comment]
So yeah. I've deliberately made it so that the scripts is only loaded when the shortcode is within the content. 

https://github.com/anttiviljami/wp-libre-form/blob/master/classes/class-cpt-wplf-form.php#L448-L452

You can just 
```
wp_enqueue_script( 'wplf-form-js' );
```

in your theme so it gets enqueued on every page nevertheless. :)

**Comment by k1sul1** [comment]
Good thinking. I'll do that.

Could you add it to the readme with #3?
