### ISSUE TITLE
Debounce parseFields() 

### ISSUE THREAD

**Issue by k1sul1** [anttiviljami/wp-libre-form#49]
When user is typing their form, detected fields are automatically added to sidebar for easy preview of what inputs exist in the form. 

There's a problem with this: it's annoying, because it's distracting. While I'm typing text to the editor, I want to focus on it, but if something is flashing in my field of view, it naturally draws my attention. 

![gif about the problem](http://i.imgur.com/Py9wj28.gif) 

If we debounce `parseFields()`, it's instantly one distraction less.

**Comment by anttiviljami** [comment]
I would like more input on this. I personally like this feature because it tells me if I forgot to name a field and gives me feedback if the form names are stupid like "field_21321", which often happens when copying forms from other sites.

**Comment by k1sul1** [comment]
Does it have to happen instantly? When you stop typing, it's 300ms (or whatever gets defined) and the feedback is there.

**Comment by anttiviljami** [comment]
I agree debouncing is a good idea. :+1: Anyone got time to implement?
