### ISSUE TITLE
Useful default subject in sent mails

### ISSUE THREAD

**Issue by k1sul1** [anttiviljami/wp-libre-form#51]
While it's not a big deal to change the default email template or subject, in it's current form the subject field doesn't make a lot of sense: 

`New submission from /`

Wouldn't `New submission to [form-name']` be better? That would break existing translations though, so least just changing the referrer to form name would require less effort.

**Comment by anttiviljami** [comment]
No I'm sorry, but my bad english senses are tingling. You don't send submissions *to* a form. You send submissions *through* it. Also, you receive submissions *from* forms, hence the phrasing here.

**Comment by anttiviljami** [comment]
Can any polyglots comment on this?

**Comment by k1sul1** [comment]
That was just an example, the title can be practically anything, but do we agree that `New submission from /` is not a good subject?

**Comment by anttiviljami** [comment]
I don't agree. :)

**Comment by timiwahalahti** [comment]
Do we agree that subject should contain submission ID to prevent messages being chained?

**Comment by k1sul1** [comment]
Yes. Form submissions are unique, they shouldn't chain. 

If someone wants chaining, they can always set their own title, and implementing #52 should allow it to be done on a form basis.

**Comment by anttiviljami** [comment]
New default subject format is: 

`[%submission_id%]: New submission from %referrer%`
