### ISSUE TITLE
Form specific actions and filters

### ISSUE THREAD

**Issue by k1sul1** [anttiviljami/wp-libre-form#52]
There's no way to set actions or filters on invidual forms.

Easily solvable though: 

`apply_filters( 'wplf_email_copy_to', $to )`

=>
```
if ( has_filter( "wplf_{$form_id}_email_copy_to" ) ) {
  apply_filters( "wplf_{$form_id}_email_copy_to", $to );
} else {
  apply_filters( "wplf_email_copy_to", $to );
}
```

**Comment by timiwahalahti** [comment]
You can use `wplf_email_copy_to` and in function that gets driven just `$_POST['_form_id']` to determine if we're in some form that needs to be handled differently.

Maybe a own filter for every form would be more clear, but then you can't use dynamic options to select forms where some action needs to run. It can become a problem in some use cases.

**Comment by anttiviljami** [comment]
I agree. ID within filter seems like it's a pretty standard way of doing stuff. I like having both options. @k1sul1 can you implement ? :)

**Comment by k1sul1** [comment]
Yeah I'm a _bit_ busy at the moment, but I can look into it in the near future.

**Comment by anttiviljami** [comment]
Just make sure you get paid for your libre forms work :)
