### ISSUE TITLE
Resend copy of submission from dashboard

### ISSUE THREAD

**Issue by timiwahalahti** [anttiviljami/wp-libre-form#57]
It would be useful to have way to resend copy of submission email from dashboard. To achieve this, `wplf_email_copy_to`needs to be saved on every submission to it's metadata. This way there won't be problems if form gets removed or email address changes.

Using bulk actions could be one, and possibly fastest and most intuitive, way to add this functionality.

**Comment by anttiviljami** [comment]
I agree. Please implement. :)

**Comment by anttiviljami** [comment]
This feature is now available as a bulk action!
