### ISSUE TITLE
Enqueue JS within shortcode

### ISSUE THREAD

**Issue by ideag** [anttiviljami/wp-libre-form#60]
I can see that you are currently conditionally loading JS when the shortcode is present within post content. That means developers have to manually enqueue scripts if they use the form anywhere else in the site - widgets, templates, etc. 

But since the JS is footer-based, why not just enqueue it within shortcode method, so it gets loaded anytime someone uses the shortcode, no matter where?

**Comment by anttiviljami** [comment]
Sounds logical! I don't see any reason why this would cause issues, but will gather some feedback first...

Thanks for the PR!

**Comment by ideag** [comment]
My pleasure. I love the premise for this plugin and I hope it will gain traction with developers in time.

**Comment by ideag** [comment]
This makes the readme section `Using the shortcode outside post content` obsolete, so that should probablu be removed.

**Comment by anttiviljami** [comment]
:+1: a0bc975
