### ISSUE TITLE
Form preview page form output differs from actual page output

### ISSUE THREAD

**Issue by k1sul1** [anttiviljami/wp-libre-form#66]
When previewing the form with the built-in preview, line breaks are translated into <br> tags and so on. 

Visualisation: 

Using the form preview:
![image](https://cloud.githubusercontent.com/assets/2719615/26821144/1a9ec996-4aae-11e7-96ab-f9cb82829174.png)

Form included on a page:
![image](https://cloud.githubusercontent.com/assets/2719615/26821127/08fd1e9a-4aae-11e7-96c4-a3437983680f.png)

**Comment by anttiviljami** [comment]
That's odd. This should address the issue. https://github.com/anttiviljami/wp-libre-form/commit/871932306ac477431151583c6c15d9e18156a02e

Are you on the newest version?

**Comment by k1sul1** [comment]
Not sure. Running composer update, will report back.

**Comment by k1sul1** [comment]
Yes, I'm on 1.2. That's probably it. 

Composer broke production in the process of updating so I'm stuck with this version for a while.

**Comment by anttiviljami** [comment]
:+1: Closing the issue since this is fixed in 1.4.
