### ISSUE TITLE
Allow customizing form attributes 

### ISSUE THREAD

**Issue by k1sul1** [anttiviljami/wp-libre-form#9]
Currently there is no way to customize the form attributes like autocomplete. I added the multipart checking in #7, but if I'd like to add said autocomplete attribute, I'm out of luck. 

If you echo the form manually in code you can always edit the output, but that's the only way. How about using the shortcode for this? Every attribute that isn't recognized could be passed as an attribute to the form element?

**Comment by anttiviljami** [comment]
An option I've been toying around with has been the idea to allow the <form> tag in the form content, but then just dynamically add and overwrite the mandatory form attributes to whatever <form> already has within post_content. 

This would however require some DOM manipulation within PHP, which is quite dreadful.

**Comment by anttiviljami** [comment]
I would love it if you could just read in all the attributes of the shortcode and directly add them to the `<form>` tag. Is that possible though?

**Comment by k1sul1** [comment]
Using `extract()` it should be? Just filter out the "known" attributes.

I know, `extract()` is pretty evil and should be avoided at all costs, but for the greater good?

**Comment by anttiviljami** [comment]
I don't think we would need extract for this. It's actually just easier to loop through all attributes passed to the shortcode if they all get passed in the . Do they?

In my understanding, `shortcode_atts()` requires you to pre-define all supported attributes.

**Comment by k1sul1** [comment]
If we can avoid using extract, we should do that, but I'm not exactly sure if we can just loop through the attributes freely...

**Comment by anttiviljami** [comment]
I still don't understand how extract would help here, but sure :)

**Comment by k1sul1** [comment]
`extract()` is so bad that we (I) should just ditch the idea about it completely.

If we can't loop (freely) through the attributes, how about a compromise? 

`[libre-form id='6' attributes='novalidate="true" autocomplete="off" data-doge="cate"']`

**Comment by anttiviljami** [comment]
Yep. That's what I was after. :/

**Comment by k1sul1** [comment]
I can't think of anything else but adding a separate input for this, if we can't use quotes in shortcodes or loop through the attributes freely.

Time for a WP core commit?

**Comment by jpeltoniemi** [comment]
Wouldn't @anttiviljami's idea work just fine? I mean looping through all attributes and pass all unused ones to the form tag.

shortcode_atts() doesn't like that but you don't have to use it anyway. (No one likes my cranky opinions but) in my opinion it's a step that only adds needless complexity and limits what you can do for no good reason. You can take care of the defaults parameters yourself usually with a simple array_merge() and can even pass threm through the standard filtering.

https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-includes/shortcodes.php#L530

**Comment by anttiviljami** [comment]
@jpeltoniemi That was exactly my original thought. If that's possible then we should definitely just do that.

**Comment by anttiviljami** [comment]
Yep. It was possible.

You can now just

```
[libre-form id="1" my-custom-attr="awesome-data"]
```
